batchsz: 50
preproc: 
  mxlen: 100
  rev: false
  clean: true
backend: keras
dataset: SST2
loader: 
  reader_type: default
unif: 0.25
model:
  sep: true
  model_type: sepcnn 
  filtsz: 3 
  cmotsz: 100
  dropout: 0.5
  finetune: true
word_embeddings: 
  label: w2v-gn
train: 
  epochs: 20 
  optim: adam
  eta: 0.0001
  model_base: ./models/sst2
  early_stopping_metric: acc
  verbose: true


